#!/usr/bin/env bash

mkdir -p ../src/com/wildlava/skydivingformationslite

sed -e 's/com.wildlava.skydivingformations\./com.wildlava.skydivingformationslite./g' -e 's/com.wildlava.skydivingformations;/com.wildlava.skydivingformationslite;/g' ../full_version/src/com/wildlava/skydivingformations/FormationBrowser.java > ../src/com/wildlava/skydivingformationslite/FormationBrowser.java

sed -e 's/com.wildlava.skydivingformations\./com.wildlava.skydivingformationslite./g' -e 's/com.wildlava.skydivingformations;/com.wildlava.skydivingformationslite;/g' ../full_version/src/com/wildlava/skydivingformations/DiveViewer.java > ../src/com/wildlava/skydivingformationslite/DiveViewer.java

sed -e 's/Skydiving Formations/Skydiving Formations Lite/g' ../full_version/res/values/strings.xml > ../res/values/strings.xml
sed -e 's/Skydiving Formations/Skydiving Formations Lite/g' ../full_version/res/values-large/strings.xml > ../res/values-large/strings.xml

sed -e 's/SkydivingFormations/SkydivingFormationsLite/g' ../full_version/build.xml > ../build.xml

sed -e 's/com.wildlava.skydivingformations/com.wildlava.skydivingformationslite/g' ../full_version/AndroidManifest.xml > ../AndroidManifest.xml
